name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Deploy
      run: |
        SSHPATH="$HOME/.ssh"
        mkdir "$SSHPATH"
        echo ${{ secrets.SINGLE_LINE_KEY }} > "$SSHPATH/key"
        chmod 600 "$SSHPATH/key"
        cat $SSHPATH/key
        SERVER_DEPLOY_STRING="ubuntu@3.8.119.144:/home/ubuntu/dndearall"
        sh -c "rsync -rltgoDzvO --delete -e 'ssh -i $SSHPATH/key -o StrictHostKeyChecking=no -p 22' $GITHUB_WORKSPACE/ $SERVER_DEPLOY_STRING"
