name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo ${{ secrets.HOST }}
    - name: Deploy
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: "35.178.167.76"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~
          ls -a
