name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Deploy
      run: |
        SSHPATH="$HOME/.ssh"
        mkdir "$SSHPATH"
        printf '-----BEGIN RSA PRIVATE KEY-----\n MIIEpAIBAAKCAQEAnLU0PdrdO+Zck8nPBxfxLdKkKpem2kNkENbJPNdFoGXTR7pF\n EvnGGVLPp2p/YStA3vu+1SM5jyF57ETEF3qMRxg0d1S7kQh1yAjiaki4gk8OAJCo\n ELKHuAE11MF2yQWC/7K57wWzavkYEJ2ceXkwbt5B0+7ONUOBTHlfLvt50GQVedMk\n 9YMFgeGPXRvHQKEX7kjBTDRq7aClDSwt+yAKOpTlLdtssbkajnmwCdHdd7SHCEbc\n D2hXETtnzukeIz4R+acd/jylN+u7/Zbhwgf6QBInuhMnEUJP3Lwd6vL8G388IL6K\n +CE1FYaVF/Q3hj7dOXJbzf23ujWFHSzyBs4RvwIDAQABAoIBAB6WX/QS3Evs0vUl\n 1vsTeUfwbYrCvxarQMTop67wde6w8WR2vzTM/BXFTDLpXqOgxbDAgqcnkPyXFC1B\n 3uSWTvsxhkwkhdfxRswcr9T/DMSimaESmztnHYaU9eTpPj5OjRtLz28QNc0Tgdb8\n bKZpOULqrv6nBijvXDWJG0MYYtaB5F42hrpB7k2wg0eJ02hydSmeLFjmFXny02K1\n lnBPogjSQSC9Tv35vGhAa2wFALCyGvKk6bK8MZ1K6e3FkgKjsupyFTIvlXBtF5mI\n 0w9k3GWrQLaAcURretYvc/ExEDV8NgORt+e/ozCWvcpxRcHxm4uuXlzyROXaUUfQ\n SzoBYYECgYEAyU8pNg7DilwE9iIxyuRIDv8+P3uT0y/tC1TSHVolCQ6kxsOo/Ir1\n ySLCT0srUWOv78QfbqNyFN5BBeoZORx7pTwLnVdD54F16s/q8hmwVFjguxLCmGD7\n YXh4axKskwLdPgc3KYhV3BEjGexYHuVfi5VShw0fCLAlZw4YBP0hvbcCgYEAx0gQ\n dV6mVYgv1MlNB1y18NZRodqBPuKEvpesA2HwjRcKBBk3ug1K4Ae3n+U557OU7aAN\n 4nZAI0Ujiy+WvkcqYO4thV6rvY1sh+FLn8NmnyDWCigsDybQ880+iGfI3TKkAPxl\n Xq+F9zEEkwBmx2Sv+sLTQyf2Lnn9FTX0XWHLzDkCgYEAvuiSlZBkwmbH0b/V5qqc\n 55QJrVx9cQ8HRvK2nF1rt+4qN9FABdemhYuwKFCKERJvu/sLL/pS6xVnJru+Fdo8\n LBQIk7s5S2gLspZhIh1YinULEn4VCzsVynbcA/besEBMHlHrbzi67AtYdXIck5hF\n BvOiIy8/WhbqMZQ9FSYVhHsCgYAdNA5VZN1zQ1XfFPDY11lCReYIlgDCumdBlvB6\n PmwGAQ5Ss29bMH98fSUHpYvqzIJSoFXojfOwN32R9BNfJwaq1byOAuWgDY2ODBIN\n A5GSWDmFm4V5YvLUB4vWaX8iCz3FdzdTvN0g8Gn/MNve9H5lfQ+Ak+abwPy5kwKQ\n fLhk4QKBgQCrBw8PhowEESfRc/PIltlIowkbogA5nqPnw99gtaxdOrH3pA5hgFgX\n kXX/IL32fdRVszPUsIvgONJ07ocwSnE+pZ3eCJesUj4u8mIq8N0kCiT5fVI3fdBg\n lMnhVfzJbQxj6/JvNf8tPlEYIsJOg4ToOAMQKXIUxsPqdjVxNuZ23w==\n -----END RSA PRIVATE KEY-----\n' > "$SSHPATH/key"
        chmod 600 "$SSHPATH/key"
        cat $SSHPATH/key
        SERVER_DEPLOY_STRING="ubuntu@3.8.119.144:/home/ubuntu/dndearall"
        sh -c "rsync -rltgoDzvO --delete -e 'ssh -i $SSHPATH/key -o StrictHostKeyChecking=no -p 22' $GITHUB_WORKSPACE/ $SERVER_DEPLOY_STRING"
