name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: cache
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Cache cross-env
      id: cross-env-cache
      uses: actions/cache@v1
      with:
        path: $GITHUB_WORKSPACE/node_modules/.bin/cross-env
        key: ${{ runner.os }}-cross-env-${{ hashFiles('node_modules/.bin/cross-env') }}

    - name: Install cross-env
      if: steps.cross-env-cache.outputs.cache-hit != 'true'
      run: yarn add cross-env --dev

    - name: Install Yarn dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    
    - name: Setup .env
      run: echo "VUE_APP_API_URL=https://api.dndearall.com" > $GITHUB_WORKSPACE/.env

    - name: Build
      run: yarn run build

    - name: Deploy
      run: |
        SSHPATH="$HOME/.ssh"
        mkdir "$SSHPATH"
        echo "${{ secrets.KEY }}" > "$SSHPATH/key"
        chmod 600 "$SSHPATH/key"
        SERVER_DEPLOY_STRING="${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET }}"
        sh -c "rsync -rltgoDzvO --delete -e 'ssh -i $SSHPATH/key -o StrictHostKeyChecking=no -p 22' $GITHUB_WORKSPACE/dist/ $GITHUB_WORKSPACE/.env $SERVER_DEPLOY_STRING"
